# Stoneburner, Kurt
- ## DSC 630 - Week XX

In [1]:
from datetime import datetime
import os
import sys
# //*** Imports and Load Data
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

#//*** Use the whole window in the IPYNB editor
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

#//*** Maximize columns and rows displayed by pandas
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

Marketing References:

https://thesportjournal.org/article/the-effects-of-promotions-on-attendance-in-professional-baseball/

https://sabr.org/journal/article/what-do-your-fans-want-attendance-correlations-with-performance-ticket-prices-and-payroll-factors/

https://engagedscholarship.csuohio.edu/cgi/viewcontent.cgi?article=1948&context=etdarchive

In [2]:
#//*** Read Raw CSV File
df = pd.read_csv("z_wk02_dodgers.csv")

df.head(5)

,month,day,attend,day_of_week,opponent,temp,skies,day_night,cap,shirt,fireworks,bobblehead
0,APR,10,56000,Tuesday,Pirates,67,Clear,Day,NO,NO,NO,NO
1,APR,11,29729,Wednesday,Pirates,58,Cloudy,Night,NO,NO,NO,NO
2,APR,12,28328,Thursday,Pirates,57,Cloudy,Night,NO,NO,NO,NO
3,APR,13,31601,Friday,Padres,54,Cloudy,Night,NO,NO,YES,NO
4,APR,14,46549,Saturday,Padres,57,Cloudy,Night,NO,NO,NO,NO

In [3]:
#//*** Convert month day to date
#//*** iPython test to only run once
if 'month' in df.columns:
    
    #//*** Build an object to handle renaming
    rename_month = {
        'APR' : "April",
        'MAY' : "May",
        'JUN' : 'June',
        'JUL' : 'July',
        'AUG' : 'August',
        'SEP' : 'September',
        'OCT' : 'October',
    }

    #//*** Rename month based on rename_month
    for key,value in rename_month.items():
        df['month'] = df['month'].str.replace(key,value)

    #//*** Convert Day to String and add leading zero
    df['day'] = df['day'].astype(str).str.zfill(2)

    #//*** Build Date Object from Month and Day Columns
    date_list = []

    #//*** Loop through each row, build date value with strptime, and add value to list
    for row in df.iterrows():
        date_list.append(datetime.strptime(f"{row[1]['month']} {row[1]['day']} 2012","%B %d %Y"))

    #//*** Add Date Column based on list
    df['date'] = pd.Series(date_list)
    
    #//*** Reorder columns, Date First, Drop Month & Day
    df = df [['date'] + list(df.columns[2:-1])]

df

,date,attend,day_of_week,opponent,temp,skies,day_night,cap,shirt,fireworks,bobblehead
0,2012-04-10,56000,Tuesday,Pirates,67,Clear,Day,NO,NO,NO,NO
1,2012-04-11,29729,Wednesday,Pirates,58,Cloudy,Night,NO,NO,NO,NO
2,2012-04-12,28328,Thursday,Pirates,57,Cloudy,Night,NO,NO,NO,NO
3,2012-04-13,31601,Friday,Padres,54,Cloudy,Night,NO,NO,YES,NO
4,2012-04-14,46549,Saturday,Padres,57,Cloudy,Night,NO,NO,NO,NO
5,2012-04-15,38359,Sunday,Padres,65,Clear,Day,NO,NO,NO,NO
6,2012-04-23,26376,Monday,Braves,60,Cloudy,Night,NO,NO,NO,NO
7,2012-04-24,44014,Tuesday,Braves,63,Cloudy,Night,NO,NO,NO,NO
8,2012-04-25,26345,Wednesday,Braves,64,Cloudy,Night,NO,NO,NO,NO
9,2012-04-27,44807,Friday,Nationals,66,Clear,Night,NO,NO,YES,NO
10,2012-04-28,54242,Saturday,Nationals,71,Clear,Night,NO,NO,NO,YES
11,2012-04-29,48753,Sunday,Nationals,74,Clear,Day,NO,YES,NO,NO
12,2012-05-07,43713,Monday,Giants,67,Clear,Night,NO,NO,NO,NO
13,2012-05-08,32799,Tuesday,Giants,75,Clear,Night,NO,NO,NO,NO
14,2012-05-09,33993,Wednesday,Giants,71,Clear,Night,NO,NO,NO,NO
15,2012-05-11,35591,Friday,Rockies,65,Clear,Night,NO,NO,YES,NO
16,2012-05-12,33735,Saturday,Rockies,65,Clear,Night,NO,NO,NO,NO
17,2012-05-13,49124,Sunday,Rockies,70,Clear,Day,NO,NO,NO,NO
18,2012-05-14,24312,Monday,Snakes,67,Clear,Night,NO,NO,NO,NO
19,2012-05-15,47077,Tuesday,Snakes,70,Clear,Night,NO,NO,NO,YES
20,2012-05-18,40906,Friday,Cardinals,64,Clear,Night,NO,NO,YES,NO
21,2012-05-19,39383,Saturday,Cardinals,67,Clear,Night,NO,NO,NO,NO
22,2012-05-20,44005,Sunday,Cardinals,77,Clear,Night,NO,NO,NO,NO
23,2012-05-25,36283,Friday,Astros,59,Cloudy,Night,NO,NO,YES,NO
24,2012-05-26,36561,Saturday,Astros,61,Cloudy,Night,NO,NO,NO,NO
25,2012-05-27,33306,Sunday,Astros,70,Clear,Day,NO,NO,NO,NO
26,2012-05-28,38016,Monday,Brewers,73,Clear,Night,NO,NO,NO,NO
27,2012-05-29,51137,Tuesday,Brewers,74,Clear,Night,NO,NO,NO,YES
28,2012-05-30,25509,Wednesday,Brewers,69,Clear,Night,NO,NO,NO,NO
29,2012-05-31,26773,Thursday,Brewers,70,Clear,Night,NO,NO,NO,NO
30,2012-06-11,50559,Monday,Angels,68,Clear,Night,NO,YES,NO,NO
31,2012-06-12,55279,Tuesday,Angels,66,Cloudy,Night,NO,NO,NO,YES
32,2012-06-13,43494,Wednesday,Angels,67,Clear,Night,NO,NO,NO,NO
33,2012-06-15,40432,Friday,White Sox,67,Clear,Night,NO,NO,YES,NO
34,2012-06-16,45210,Saturday,White Sox,68,Clear,Night,NO,NO,NO,NO
35,2012-06-17,53504,Sunday,White Sox,74,Clear,Day,NO,NO,NO,NO
36,2012-06-28,49006,Thursday,Mets,75,Clear,Night,NO,NO,NO,YES
37,2012-06-29,49763,Friday,Mets,72,Clear,Night,NO,NO,YES,NO
38,2012-06-30,44217,Saturday,Mets,78,Clear,Day,NO,NO,NO,NO
39,2012-07-01,55359,Sunday,Mets,75,Clear,Night,NO,NO,NO,YES
40,2012-07-02,34493,Monday,Reds,70,Clear,Night,NO,NO,NO,NO
41,2012-07-03,33884,Tuesday,Reds,70,Cloudy,Night,YES,NO,NO,NO
42,2012-07-04,53570,Wednesday,Reds,70,Clear,Night,NO,NO,YES,NO
43,2012-07-13,43873,Friday,Padres,76,Cloudy,Night,NO,NO,YES,NO
44,2012-07-14,54014,Saturday,Padres,75,Clear,Night,NO,NO,NO,YES
45,2012-07-15,39715,Sunday,Padres,77,Clear,Day,NO,NO,NO,NO
46,2012-07-16,32238,Monday,Phillies,67,Clear,Night,NO,NO,NO,NO
47,2012-07-17,53498,Tuesday,Phillies,70,Clear,Night,NO,NO,NO,NO
48,2012-07-18,39955,Wednesday,Phillies,80,Cloudy,Day,NO,NO,NO,NO
49,2012-07-30,33180,Monday,Snakes,73,Clear,Night,NO,NO,NO,NO
50,2012-07-31,52832,Tuesday,Snakes,75,Cloudy,Night,NO,NO,NO,YES
51,2012-08-01,36596,Wednesday,Snakes,79,Clear,Day,NO,NO,NO,NO
52,2012-08-03,43537,Friday,Cubs,73,Clear,Night,NO,NO,YES,NO
53,2012-08-04,46588,Saturday,Cubs,73,Cloudy,Night,NO,NO,NO,NO
54,2012-08-05,42495,Sunday,Cubs,83,Clear,Day,YES,NO,NO,NO
55,2012-08-06,32659,Monday,Rockies,79,Clear,Night,NO,NO,NO,NO
56,2012-08-07,55024,Tuesday,Rockies,80,Clear,Night,NO,NO,NO,YES
57,2012-08-08,37084,Wednesday,Rockies,84,Clear,Night,NO,NO,NO,NO
58,2012-08-20,36878,Monday,Giants,80,Clear,Night,NO,NO,NO,NO
59,2012-08-21,56000,Tuesday,Giants,75,Clear,Night,NO,NO,NO,YES
60,2012-08-22,40173,Wednesday,Giants,75,Clear,Night,NO,NO,NO,NO
61,2012-08-24,39805,Friday,Marlins,71,Clear,Night,NO,NO,YES,NO
62,2012-08-25,40284,Saturday,Marlins,70,Clear,Night,NO,NO,NO,NO
63,2012-08-26,41907,Sunday,Marlins,81,Clear,Day,NO,NO,NO,NO
64,2012-08-30,54621,Thursday,Snakes,80,Clear,Night,NO,NO,NO,YES
65,2012-08-31,37622,Friday,Snakes,77,Clear,Night,NO,NO,YES,NO
66,2012-09-01,35992,Saturday,Snakes,81,Clear,Night,NO,NO,NO,NO
67,2012-09-02,31607,Sunday,Snakes,89,Clear,Day,NO,NO,NO,NO
68,2012-09-03,33540,Monday,Padres,84,Cloudy,Night,NO,NO,NO,NO
69,2012-09-04,40619,Tuesday,Padres,78,Clear,Night,NO,YES,NO,NO
70,2012-09-05,50560,Wednesday,Padres,77,Cloudy,Night,NO,NO,NO,NO
71,2012-09-13,43309,Thursday,Cardinals,80,Clear,Night,NO,NO,NO,NO
72,2012-09-14,40167,Friday,Cardinals,85,Clear,Night,NO,NO,YES,NO
73,2012-09-15,42449,Saturday,Cardinals,95,Clear,Night,NO,NO,NO,NO
74,2012-09-16,35754,Sunday,Cardinals,86,Clear,Day,NO,NO,NO,NO
75,2012-09-28,37133,Friday,Rockies,77,Clear,Night,NO,NO,YES,NO
76,2012-09-29,40724,Saturday,Rockies,84,Cloudy,Night,NO,NO,NO,NO
77,2012-09-30,35607,Sunday,Rockies,95,Clear,Day,NO,NO,NO,NO
78,2012-10-01,33624,Monday,Giants,86,Clear,Night,NO,NO,NO,NO
79,2012-10-02,42473,Tuesday,Giants,83,Clear,Night,NO,NO,NO,NO
80,2012-10-03,34014,Wednesday,Giants,82,Cloudy,Night,NO,NO,NO,NO

In [27]:
#//*** Keep a copy of the original Dataframe before creating Integer Categoricals
df_cat = df.copy()

#//*** Convert Day of Week to Categorical Integer
day_of_week = {
    "Monday" : "1",
    "Tuesday" : "2",
    "Wednesday" : "3",
    "Thursday" : "4",
    "Friday" : "5",
    "Saturday" : "6",
    "Sunday" : "7"
}

#//*** Create Temp series
tds = pd.Series(df['day_of_week'].astype('str'))

#//*** Replace day_of week values with Integers
for key,value in day_of_week.items():
    tds = tds.str.replace(key,value)

#//*** tds to day_of_week
df_cat['day_of_week'] = tds

df_cat
#//*** Convert remaining columns to integer Categoricals
convert_cols = ["opponent","skies","day_night","cap","shirt","fireworks","bobblehead"]

#//*** Dictionary to hold Categorical definitions
df_dict = {}

#//*** Convert each column into a unique integer
#//*** 1.) Get Column unique Values
#//*** 2.) Enumerate creates a Tuple containing an incremental integer and the unique value
#//*** 3.) Convert Enumerated values into a dictionary
#//*** 4.) Add the Dictionary to df_dict using the col as key
for col in convert_cols:
    df_dict[col] = dict(enumerate(df_cat[col].unique()))
    
#//*** Loop through df_dict and replace values with integer keys

for col, value_dict in df_dict.items():
    print(value_dict)
    for key,value in value_dict.items():
        
        df_cat[col] = df_cat[col].str.replace(value,str(key))
    df_cat[col] = df_cat[col].astype(int)
df_cat

{0: '0', 1: '1', 2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9', 10: '10', 11: '11', 12: '12', 13: '13', 14: '14', 15: '15', 16: '16'}
{0: '0', 1: '1'}
{0: '0', 1: '1'}
{0: '0', 1: '1'}
{0: '0', 1: '1'}
{0: '0', 1: '1'}
{0: '0', 1: '1'}

,date,attend,day_of_week,opponent,temp,skies,day_night,cap,shirt,fireworks,bobblehead
0,2012-04-10,56000,2,0,67,0,0,0,0,0,0
1,2012-04-11,29729,3,0,58,1,1,0,0,0,0
2,2012-04-12,28328,4,0,57,1,1,0,0,0,0
3,2012-04-13,31601,5,1,54,1,1,0,0,1,0
4,2012-04-14,46549,6,1,57,1,1,0,0,0,0
5,2012-04-15,38359,7,1,65,0,0,0,0,0,0
6,2012-04-23,26376,1,2,60,1,1,0,0,0,0
7,2012-04-24,44014,2,2,63,1,1,0,0,0,0
8,2012-04-25,26345,3,2,64,1,1,0,0,0,0
9,2012-04-27,44807,5,3,66,0,1,0,0,1,0
10,2012-04-28,54242,6,3,71,0,1,0,0,0,1
11,2012-04-29,48753,7,3,74,0,0,0,1,0,0
12,2012-05-07,43713,1,4,67,0,1,0,0,0,0
13,2012-05-08,32799,2,4,75,0,1,0,0,0,0
14,2012-05-09,33993,3,4,71,0,1,0,0,0,0
15,2012-05-11,35591,5,5,65,0,1,0,0,1,0
16,2012-05-12,33735,6,5,65,0,1,0,0,0,0
17,2012-05-13,49124,7,5,70,0,0,0,0,0,0
18,2012-05-14,24312,1,6,67,0,1,0,0,0,0
19,2012-05-15,47077,2,6,70,0,1,0,0,0,1
20,2012-05-18,40906,5,7,64,0,1,0,0,1,0
21,2012-05-19,39383,6,7,67,0,1,0,0,0,0
22,2012-05-20,44005,7,7,77,0,1,0,0,0,0
23,2012-05-25,36283,5,8,59,1,1,0,0,1,0
24,2012-05-26,36561,6,8,61,1,1,0,0,0,0
25,2012-05-27,33306,7,8,70,0,0,0,0,0,0
26,2012-05-28,38016,1,9,73,0,1,0,0,0,0
27,2012-05-29,51137,2,9,74,0,1,0,0,0,1
28,2012-05-30,25509,3,9,69,0,1,0,0,0,0
29,2012-05-31,26773,4,9,70,0,1,0,0,0,0
30,2012-06-11,50559,1,10,68,0,1,0,1,0,0
31,2012-06-12,55279,2,10,66,1,1,0,0,0,1
32,2012-06-13,43494,3,10,67,0,1,0,0,0,0
33,2012-06-15,40432,5,11,67,0,1,0,0,1,0
34,2012-06-16,45210,6,11,68,0,1,0,0,0,0
35,2012-06-17,53504,7,11,74,0,0,0,0,0,0
36,2012-06-28,49006,4,12,75,0,1,0,0,0,1
37,2012-06-29,49763,5,12,72,0,1,0,0,1,0
38,2012-06-30,44217,6,12,78,0,0,0,0,0,0
39,2012-07-01,55359,7,12,75,0,1,0,0,0,1
40,2012-07-02,34493,1,13,70,0,1,0,0,0,0
41,2012-07-03,33884,2,13,70,1,1,1,0,0,0
42,2012-07-04,53570,3,13,70,0,1,0,0,1,0
43,2012-07-13,43873,5,1,76,1,1,0,0,1,0
44,2012-07-14,54014,6,1,75,0,1,0,0,0,1
45,2012-07-15,39715,7,1,77,0,0,0,0,0,0
46,2012-07-16,32238,1,14,67,0,1,0,0,0,0
47,2012-07-17,53498,2,14,70,0,1,0,0,0,0
48,2012-07-18,39955,3,14,80,1,0,0,0,0,0
49,2012-07-30,33180,1,6,73,0,1,0,0,0,0
50,2012-07-31,52832,2,6,75,1,1,0,0,0,1
51,2012-08-01,36596,3,6,79,0,0,0,0,0,0
52,2012-08-03,43537,5,15,73,0,1,0,0,1,0
53,2012-08-04,46588,6,15,73,1,1,0,0,0,0
54,2012-08-05,42495,7,15,83,0,0,1,0,0,0
55,2012-08-06,32659,1,5,79,0,1,0,0,0,0
56,2012-08-07,55024,2,5,80,0,1,0,0,0,1
57,2012-08-08,37084,3,5,84,0,1,0,0,0,0
58,2012-08-20,36878,1,4,80,0,1,0,0,0,0
59,2012-08-21,56000,2,4,75,0,1,0,0,0,1
60,2012-08-22,40173,3,4,75,0,1,0,0,0,0
61,2012-08-24,39805,5,16,71,0,1,0,0,1,0
62,2012-08-25,40284,6,16,70,0,1,0,0,0,0
63,2012-08-26,41907,7,16,81,0,0,0,0,0,0
64,2012-08-30,54621,4,6,80,0,1,0,0,0,1
65,2012-08-31,37622,5,6,77,0,1,0,0,1,0
66,2012-09-01,35992,6,6,81,0,1,0,0,0,0
67,2012-09-02,31607,7,6,89,0,0,0,0,0,0
68,2012-09-03,33540,1,1,84,1,1,0,0,0,0
69,2012-09-04,40619,2,1,78,0,1,0,1,0,0
70,2012-09-05,50560,3,1,77,1,1,0,0,0,0
71,2012-09-13,43309,4,7,80,0,1,0,0,0,0
72,2012-09-14,40167,5,7,85,0,1,0,0,1,0
73,2012-09-15,42449,6,7,95,0,1,0,0,0,0
74,2012-09-16,35754,7,7,86,0,0,0,0,0,0
75,2012-09-28,37133,5,5,77,0,1,0,0,1,0
76,2012-09-29,40724,6,5,84,1,1,0,0,0,0
77,2012-09-30,35607,7,5,95,0,0,0,0,0,0
78,2012-10-01,33624,1,4,86,0,1,0,0,0,0
79,2012-10-02,42473,2,4,83,0,1,0,0,0,0
80,2012-10-03,34014,3,4,82,1,1,0,0,0,0

In [ ]:
# //*** CODE HERE