https://healthdata.gov/Hospital/COVID-19-Reported-Patient-Impact-and-Hospital-Capa/anag-cw7u

In [2]:
import pandas as pd
import requests
import numpy as np

In [3]:
outcome_url = "https://data.cdc.gov/api/views/n8mc-b4w4/rows.csv?accessType=DOWNLOAD"
outcome_url = "https://data.cdc.gov/resource/n8mc-b4w4.json"
outcome_url = "https://data.cdc.gov/api/views/n8mc-b4w4/rows.csv?accessType=DOWNLOAD&api_foundry=true"
outcome_filename = "./raw_data/covid_outcomes.csv"
raw_outcome_filename = "./ignore/COVID-19_Case_Surveillance_Public_Use_Data_with_Geography.csv"

In [2]:
"""
print(f"Downloading {outcome_url}")
response = requests.get(outcome_url)
if response.ok:
    print(f"{outcome_url} Downloaded")
    f = open(outcome_filename, "w")
    f.write(response.text)
    f.close()
    print(f"{outcome_filename} Data Written to file.")
"""
print()

In [6]:
df = pd.read_csv(raw_outcome_filename)

C:\Users\family\AppData\Local\Temp/ipykernel_18996/2860339106.py:1: DtypeWarning: Columns (3,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(raw_outcome_filename)

In [7]:
df.head()

,case_month,res_state,state_fips_code,res_county,county_fips_code,age_group,sex,race,ethnicity,case_positive_specimen_interval,case_onset_interval,process,exposure_yn,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2022-02,CA,6.0,SANTA CLARA,6085.0,18 to 49 years,Female,White,Non-Hispanic/Latino,NaN,NaN,Missing,Missing,Laboratory-confirmed case,Unknown,Missing,Missing,Missing,NaN
1,2022-01,NY,36.0,MONROE,36055.0,18 to 49 years,Female,Missing,Unknown,NaN,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,No,NaN
2,2021-12,WA,53.0,KING,53033.0,18 to 49 years,Male,Missing,Unknown,0.0,0.0,Missing,Missing,Laboratory-confirmed case,Symptomatic,Unknown,Missing,Missing,NaN
3,2021-12,PA,42.0,YORK,42133.0,18 to 49 years,Female,White,Non-Hispanic/Latino,0.0,0.0,Missing,Missing,Probable Case,Symptomatic,Unknown,Unknown,Unknown,NaN
4,2020-07,CA,6.0,FRESNO,6019.0,50 to 64 years,Female,White,Non-Hispanic/Latino,NaN,0.0,Missing,Missing,Laboratory-confirmed case,Symptomatic,No,Missing,Missing,NaN

In [14]:
for group in df.groupby('res_state'):
    print(group[0])
    group[1].to_pickle(f"./raw_data/{group[0]}_covid_people.pkl.zip")

AK
AL
AR
AZ
CA
CO
CT
DC
DE
FL
GA
GU
HI
IA
ID
IL
IN
KS
KY
LA
MA
MD
ME
MI
MN
MO
MS
MT
NC
ND
NE
NH
NJ
NM
NV
NY
OH
OK
OR
PA
PR
RI
SC
SD
TN
TX
UT
VA
VI
VT
WA
WI
WV
WY

In [3]:
tdf = pd.read_pickle("./raw_data/AK_covid_people.pkl.zip")
#//*** Drop Rows with NaN county FIPS Code
tdf = tdf.dropna(subset="county_fips_code")

tdf

,case_month,res_state,state_fips_code,res_county,county_fips_code,age_group,sex,race,ethnicity,case_positive_specimen_interval,case_onset_interval,process,exposure_yn,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
26747742,2021-09,AK,2.0,FAIRBANKS NORTH STAR,2090.0,18 to 49 years,Female,White,Hispanic/Latino,NaN,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
26747759,2021-09,AK,2.0,MATANUSKA-SUSITNA,2170.0,0 - 17 years,Male,White,Hispanic/Latino,NaN,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
26748241,2021-09,AK,2.0,ANCHORAGE,2020.0,18 to 49 years,Female,Multiple/Other,Hispanic/Latino,NaN,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
26748256,2021-09,AK,2.0,KENAI PENINSULA,2122.0,18 to 49 years,Female,White,Hispanic/Latino,NaN,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
26748544,2021-09,AK,2.0,JUNEAU,2110.0,18 to 49 years,Female,Multiple/Other,NaN,NaN,NaN,Missing,Missing,Probable Case,Missing,Missing,Missing,Missing,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66922764,2022-01,AK,2.0,ANCHORAGE,2020.0,18 to 49 years,Male,White,Unknown,NaN,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
66922953,2022-01,AK,2.0,ANCHORAGE,2020.0,18 to 49 years,Male,White,Unknown,NaN,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
66923139,2022-01,AK,2.0,ANCHORAGE,2020.0,18 to 49 years,Male,White,Unknown,NaN,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
66923328,2022-01,AK,2.0,ANCHORAGE,2020.0,18 to 49 years,Male,White,Unknown,NaN,NaN,Missing,Missing,Probable Case,Missing,Missing,Missing,Missing,NaN
66923517,2022-01,AK,2.0,ANCHORAGE,2020.0,18 to 49 years,Male,White,Unknown,NaN,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN

In [26]:

tdf["case_positive_specimen_interval"].unique()
tdf["case_onset_interval"].unique()
tdf["process"].unique()
tdf['hosp_yn'].unique()
tdf['death_yn'].unique()
tdf['underlying_conditions_yn'].unique()
tdf.corr()

base_cols = ["case_month","res_state","state_fips_code","res_county","county_fips_code"]

classifier_dict = {
    'age_group' : {
        -1 : np.nan,
        0 : '0 - 17 years',
        1 : '18 to 49 years',
        2 : '50 to 64 years',
        3 : '65+ years'
    }
}


tdf = pd.read_pickle("./raw_data/AK_covid_people.pkl.zip")
#//*** Drop Rows with NaN county FIPS Code
tdf = tdf.dropna(subset="county_fips_code")

for col in tdf.columns:
    if col in base_cols:
        continue
    #print (col,tdf[col].dtype)
    
    #//*** Replace Float Value NaN with -1
    if tdf[col].dtype == 'float64':
        tdf[col] = tdf[col].replace(np.nan,-1)
        #print(tdf[col].unique())
        continue
    if tdf[col].dtype == 'object':
        #//*** Replace Nan  with -1
        tdf[col] = tdf[col].replace(np.nan,-1)
        #//*** Initialize Col if needed
        if col not in classifier_dict.keys():
            #//*** Initialize -1 as NaN
            classifier_dict[col] = {
                -1 : np.nan,
            }
        
        #//*** Create integer classifier for loop_dict
        for key,value in enumerate(tdf[col].unique()):
            
            if value == -1:
                continue
            #//*** add to dictionary if Value doesn't already exist
            if value not in classifier_dict[col].values():
                
                #//*** Double Check Key doesn't exist
                if key not in classifier_dict[col].keys():
                    classifier_dict[col][key] = value
                else:
                    print(f"key {key} already exists! Something is amiss here!")
            
            #//*** Update Dictionary
            #loop_dict[key] = value
            
        #//*** Replace Values with Classifier Integer
        for key,value in classifier_dict[col].items():
            tdf[col] = tdf[col].replace(value,key)
        
        continue
        
    print(f"Unknown Column Type: {col} - {tdf[col].dtype} ")

In [57]:
print("Underlying: ",classifier_dict['underlying_conditions_yn'])
print("Death:",classifier_dict['death_yn'])
print("ICU:",classifier_dict['icu_yn'])
print("hosp:",classifier_dict['hosp_yn'])

process_cols = ['hosp_yn','icu_yn','death_yn','underlying_conditions_yn'] 
#//*** Keep relevant Columns
use_cols = base_cols + process_cols

df = pd.DataFrame()

#//*** Sum the cases by month, hate to lose the demographic data
for date_group in tdf[use_cols].groupby('case_month'):
    #print(date_group[1]['county_fips_code'].unique())
    for fips_group in date_group[1].groupby('county_fips_code'):
        #print(fips_group[0])
        
        
        #//*** Reclassify Data Again, only keep Yes Values
        for col in fips_group[1].columns:
            if col in classifier_dict.keys():
                
                for key,value in classifier_dict[col].items():
                    
                    #//*** Replace YEs with -2
                    if value == 'Yes':
                        fips_group[1][col] = fips_group[1][col].replace(key,-2)
                    else:
                        fips_group[1][col] = fips_group[1][col].replace(key,0)
                
                fips_group[1][col] = fips_group[1][col].replace(-2,1)
        #print(fips_group[1])
        #print(fips_group[1]['hosp_yn'].sum())
        tds =  fips_group[1].iloc[0].copy()
        
        
        for col in process_cols:
            
            tds[col] = fips_group[1][col].sum()
        
        df = pd.concat([df,tds],axis=1)
        
        
    
dr=df.transpose()    
print(df)

Underlying:  {-1: nan, 1: 'Yes'}
Death: {-1: nan, 0: 'Missing', 2: 'Unknown', 3: 'No', 4: 'Yes'}
ICU: {-1: nan, 0: 'Missing', 1: 'No', 2: 'Yes', 3: 'Unknown'}
hosp: {-1: nan, 0: 'Missing', 1: 'No', 2: 'Yes', 3: 'Unknown'}
                           38497217              32964343 34207339  \
case_month                  2020-03               2020-03  2020-03
res_state                        AK                    AK       AK
state_fips_code                 2.0                   2.0      2.0
res_county                ANCHORAGE  FAIRBANKS NORTH STAR   JUNEAU
county_fips_code             2020.0                2090.0   2110.0
hosp_yn                          12                     8        5
icu_yn                            7                     2        4
death_yn                          0                     0        0
underlying_conditions_yn         58                    38        9

                                 40889109   29212322              47478519  \
case_month                        2020-03    2020-04               2020-04
res_state                              AK         AK                    AK
state_fips_code                       2.0        2.0                   2.0
res_county                KENAI PENINSULA  ANCHORAGE  FAIRBANKS NORTH STAR
county_fips_code                   2122.0     2020.0                2090.0
hosp_yn                                 1          7                     1
icu_yn                                  1          3                     0
death_yn                                0          0                     0
underlying_conditions_yn               10         38                    15

                         31239570           49974753   50958368  \
case_month                2020-04            2020-04    2020-05
res_state                      AK                 AK         AK
state_fips_code               2.0                2.0        2.0
res_county                 JUNEAU  MATANUSKA-SUSITNA  ANCHORAGE
county_fips_code           2110.0             2170.0     2020.0
hosp_yn                         2                  1          8
icu_yn                          1                  1          1
death_yn                        0                  0          0
underlying_conditions_yn        7                  5         40

                                 26865218  ...   27322061  \
case_month                        2020-05  ...    2022-02
res_state                              AK  ...         AK
state_fips_code                       2.0  ...        2.0
res_county                KENAI PENINSULA  ...  ANCHORAGE
county_fips_code                   2122.0  ...     2020.0
hosp_yn                                 2  ...         30
icu_yn                                  2  ...          0
death_yn                                0  ...          0
underlying_conditions_yn               31  ...          0

                                      27304794 26946221         27158310  \
case_month                             2022-02  2022-02          2022-02
res_state                                   AK       AK               AK
state_fips_code                            2.0      2.0              2.0
res_county                FAIRBANKS NORTH STAR   JUNEAU  KENAI PENINSULA
county_fips_code                        2090.0   2110.0           2122.0
hosp_yn                                      2        0               23
icu_yn                                       0        0                0
death_yn                                     0        0                0
underlying_conditions_yn                     0        0                1

                                   26993049   33140462              33505932  \
case_month                          2022-02    2022-03               2022-03
res_state                                AK         AK                    AK
state_fips_code                         2.0        2.0                   2.0
res_county                MATANUSKA-SUSITNA  ANCHORAGE  FAIRBANKS NORTH STAR
county_fips_code                     2170.0     2020.0                2090.0
hosp_yn                                   8          7                     1
icu_yn                                    0          0                     0
death_yn                                  0          0                     0
underlying_conditions_yn                  0          1                     0

                         31785631         30182500           31116349
case_month                2022-03          2022-03            2022-03
res_state                      AK               AK                 AK
state_fips_code               2.0              2.0                2.0
res_county                 JUNEAU  KENAI PENINSULA  MATANUSKA-SUSITNA
county_fips_code           2110.0           2122.0             2170.0
hosp_yn                         1                9                  1
icu_yn                          0                0                  0
death_yn                        0                0                  0
underlying_conditions_yn        0                1                  0

[9 rows x 121 columns]

In [59]:
df.transpose()

,case_month,res_state,state_fips_code,res_county,county_fips_code,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
38497217,2020-03,AK,2.0,ANCHORAGE,2020.0,12,7,0,58
32964343,2020-03,AK,2.0,FAIRBANKS NORTH STAR,2090.0,8,2,0,38
34207339,2020-03,AK,2.0,JUNEAU,2110.0,5,4,0,9
40889109,2020-03,AK,2.0,KENAI PENINSULA,2122.0,1,1,0,10
29212322,2020-04,AK,2.0,ANCHORAGE,2020.0,7,3,0,38
...,...,...,...,...,...,...,...,...,...
33140462,2022-03,AK,2.0,ANCHORAGE,2020.0,7,0,0,1
33505932,2022-03,AK,2.0,FAIRBANKS NORTH STAR,2090.0,1,0,0,0
31785631,2022-03,AK,2.0,JUNEAU,2110.0,1,0,0,0
30182500,2022-03,AK,2.0,KENAI PENINSULA,2122.0,9,0,0,1
31116349,2022-03,AK,2.0,MATANUSKA-SUSITNA,2170.0,1,0,0,0