
    Page 161: 12-1 (The linear model I used in this chapter has the obvious drawback that it is linear and there is no reason to expect prices to change linearly over time…)
    Page 161: 12-2 (Write a definition for a class called SerialCorrelationTest that extends HypothesisTest from “HypothesisTest” on page 102…)

# Stoneburner, Kurt
- ## DSC 530 - Week 10

In [1]:
# //****************************************************************************************
# //*** Set Working Directory to thinkstats folder.
# //*** This pseudo-relative path call should work on all Stoneburner localized projects. 
# //****************************************************************************************

import os
import sys
workingPath = os.getcwd().replace("coding", "ThinkStats2\\code")
sys.path.insert(1, workingPath)
os.chdir(workingPath)

In [62]:
# //*** Imports and Load Data
#import nsfg
import thinkstats2
import thinkplot
#import first
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import math

transactions = pd.read_csv('mj-clean.csv', parse_dates=[5])
#//*** Add an index field that matches the index to help with reindexing errors
transactions['dex'] = transactions.index

#//*** Build empty array to hold average daily price 
mt_arr=np.empty(len(transactions));mt_arr.fill(np.nan)
#transactions['ppg_avg_day'] = mt_arr


transactions.head()

,city,state,price,amount,quality,date,ppg,state.name,lat,lon,dex
0,Annandale,VA,100,7.075,high,2010-09-02,14.13,Virginia,38.830345,-77.213870,0
1,Auburn,AL,60,28.300,high,2010-09-02,2.12,Alabama,32.578185,-85.472820,1
2,Austin,TX,60,28.300,medium,2010-09-02,2.12,Texas,30.326374,-97.771258,2
3,Belleville,IL,400,28.300,high,2010-09-02,14.13,Illinois,38.532311,-89.983521,3
4,Boone,NC,55,3.540,high,2010-09-02,15.54,North Carolina,36.217052,-81.687983,4

- ## Chapter 12, Exercise 1

**Exercise:**   The linear model I used in this chapter has the obvious drawback that it is linear, and there is no reason to expect prices to change linearly over time. We can add flexibility to the model by adding a quadratic term, as we did in Section 11.3.

Use a quadratic model to fit the time series of daily prices, and use the model to generate predictions. You will have to write a version of `RunLinearModel` that runs that quadratic model, but after that you should be able to reuse code from the chapter to generate predictions.

In [103]:
###//**** Original Method... Slow
#//*** Combine the data for each day and group by quality (high, med, low)

quality_unique = transactions['quality'].unique()

date_unique = transactions['date'].unique()

mt_arr=np.empty(len(transactions));mt_arr.fill(np.nan)

ppg_avg_day = pd.Series(mt_arr)
year_part = pd.Series(mt_arr)

#//*** Base values to calculate time of year
start_date = transactions['date'][0]
one_year = np.timedelta64(1, 'Y')

#//*** Divide groups by Quality
for quality_group in transactions.groupby('quality'):
    print(f"Processing Group: - {quality_group[0]}")
    
    #//*** group quality_group_df by date
    for each_day in quality_group[1].groupby('date'):
        
        #//*** Generate the mean of all values on a given day
        each_day_mean = np.mean(each_day[1]['ppg'])
        
        
        #//*** Get the date as a percentage of the current year
        loop_date = (each_day[1]['date'].iloc[0] - start) / one_year
    
        #//*** Update ppg_avg_day series
        #//*** Use the 'dex' as index 
        #for loop2_index in each_day_df['dex']:
        #    ppg_avg_day.iloc[loop2_index] = each_day_mean
        #    year_part.iloc[loop2_index] = loop_date
            
        
#//*** Add ppg_avg_day to transaction
transactions['ppg_avg_day'] = ppg_avg_day
transactions['year_part'] = year_part
transactions.head()

Processing Group: - high
Processing Group: - low
Processing Group: - medium

,city,state,price,amount,quality,date,ppg,state.name,lat,lon,dex,ppg_avg_day,year_part
0,Annandale,VA,100,7.075,high,2010-09-02,14.13,Virginia,38.830345,-77.213870,0,NaN,NaN
1,Auburn,AL,60,28.300,high,2010-09-02,2.12,Alabama,32.578185,-85.472820,1,NaN,NaN
2,Austin,TX,60,28.300,medium,2010-09-02,2.12,Texas,30.326374,-97.771258,2,NaN,NaN
3,Belleville,IL,400,28.300,high,2010-09-02,14.13,Illinois,38.532311,-89.983521,3,NaN,NaN
4,Boone,NC,55,3.540,high,2010-09-02,15.54,North Carolina,36.217052,-81.687983,4,NaN,NaN

In [90]:


print(f"{start}")

2010-09-02 00:00:00

- ## Chapter 12, Exercise 2

**Exercise:** Write a definition for a class named `SerialCorrelationTest` that extends `HypothesisTest` from Section 9.2. It should take a series and a lag as data, compute the serial correlation of the series with the given lag, and then compute the p-value of the observed correlation.

Use this class to test whether the serial correlation in raw price data is statistically significant. Also test the residuals of the linear model and (if you did the previous exercise), the quadratic model.

In [ ]:
# //*** CODE HERE

- ## Chapter X, Exercise X

In [ ]:
# //*** CODE HERE

- ## Chapter X, Exercise X

In [ ]:
# //*** CODE HERE

In [65]:
'''
###//**** Original Method... Slow
#//*** Combine the data for each day and group by quality (high, med, low)

quality_unique = transactions['quality'].unique()

date_unique = transactions['date'].unique()

mt_arr=np.empty(len(transactions));mt_arr.fill(np.nan)

ppg_avg_day = pd.Series(mt_arr)

#//*** Loop through each day
for loop_day in date_unique:
    print(f"{loop_day}")
    #//*** Loop through the quality for that given day
    for loop_quality in quality_unique:
        loop_day_qual_df = pd.DataFrame( 
            data = transactions[transactions['date'] == loop_day ][transactions['quality'] == loop_quality ], 
            index = transactions[transactions['date'] == loop_day ][transactions['quality'] == loop_quality ]['dex'])
        
        
        #//*** Check if we have quality values for a given day
        loop_mean = np.mean(loop_day_qual_df['ppg'])
        
        
        
        for index in loop_day_qual_df.index:
            ppg_avg_day.iloc[index] = loop_mean

        #transactions.loc[loop_day_qual_df.index]['ppg_avg_day'] = 100
        
        #print(f"{loop_day_qual_df.index}")
        #print(f"{len(transactions.loc[loop_day_qual_df.index])}")
        #//*** Some values will generate nan, due to no values for that day
        #if math.isnan(np.mean(loop_day_qual_df['ppg'])) :
        #    print(f"Nan: {loop_day_qual_df['ppg_avg_day']}")
        
        #transactions.loc[loop_day_qual_df.index]['ppg_avg_day']= np.mean(loop_day_qual_df['ppg'])
        #print(transactions.loc[loop_day_qual_df.index]['ppg_avg_day'])
        #print(f"{transactions.head()}")
    
    
#//*** END each Day
transactions.head()
'''

2010-09-02T00:00:00.000000000
2010-09-03T00:00:00.000000000

<ipython-input-65-a99aeaec72fb>:17: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data = transactions[transactions['date'] == loop_day ][transactions['quality'] == loop_quality ],
<ipython-input-65-a99aeaec72fb>:18: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  index = transactions[transactions['date'] == loop_day ][transactions['quality'] == loop_quality ]['dex'])

2010-09-04T00:00:00.000000000
2010-09-05T00:00:00.000000000
2010-09-06T00:00:00.000000000
2010-09-07T00:00:00.000000000
2010-09-08T00:00:00.000000000
2010-09-09T00:00:00.000000000
2010-09-10T00:00:00.000000000
2010-09-11T00:00:00.000000000
2010-09-12T00:00:00.000000000
2010-09-13T00:00:00.000000000
2010-09-14T00:00:00.000000000
2010-09-15T00:00:00.000000000
2010-09-16T00:00:00.000000000
2010-09-17T00:00:00.000000000
2010-09-18T00:00:00.000000000
2010-09-19T00:00:00.000000000
2010-09-20T00:00:00.000000000
2010-09-21T00:00:00.000000000
2010-09-22T00:00:00.000000000
2010-09-23T00:00:00.000000000
2010-09-24T00:00:00.000000000
2010-09-25T00:00:00.000000000
2010-09-26T00:00:00.000000000
2010-09-27T00:00:00.000000000
2010-09-28T00:00:00.000000000
2010-09-29T00:00:00.000000000
2010-09-30T00:00:00.000000000
2010-10-01T00:00:00.000000000
2010-10-02T00:00:00.000000000
2010-10-03T00:00:00.000000000
2010-10-04T00:00:00.000000000
2010-10-05T00:00:00.000000000
2010-10-06T00:00:00.000000000
2010-10-07T00:00:00.000000000
2010-10-08T00:00:00.000000000
2010-10-09T00:00:00.000000000
2010-10-10T00:00:00.000000000
2010-10-11T00:00:00.000000000
2010-10-12T00:00:00.000000000
2010-10-13T00:00:00.000000000
2010-10-14T00:00:00.000000000
2010-10-15T00:00:00.000000000
2010-10-16T00:00:00.000000000
2010-10-17T00:00:00.000000000
2010-10-18T00:00:00.000000000
2010-10-19T00:00:00.000000000
2010-10-20T00:00:00.000000000
2010-10-21T00:00:00.000000000
2010-10-22T00:00:00.000000000
2010-10-23T00:00:00.000000000
2010-10-24T00:00:00.000000000
2010-10-25T00:00:00.000000000
2010-10-26T00:00:00.000000000
2010-10-27T00:00:00.000000000
2010-10-28T00:00:00.000000000
2010-10-29T00:00:00.000000000
2010-10-30T00:00:00.000000000
2010-10-31T00:00:00.000000000
2010-11-01T00:00:00.000000000
2010-11-02T00:00:00.000000000
2010-11-03T00:00:00.000000000
2010-11-04T00:00:00.000000000
2010-11-05T00:00:00.000000000
2010-11-06T00:00:00.000000000
2010-11-07T00:00:00.000000000
2010-11-08T00:00:00.000000000
2010-11-09T00:00:00.000000000
2010-11-10T00:00:00.000000000
2010-11-11T00:00:00.000000000
2010-11-12T00:00:00.000000000
2010-11-13T00:00:00.000000000
2010-11-14T00:00:00.000000000
2010-11-15T00:00:00.000000000
2010-11-16T00:00:00.000000000
2010-11-17T00:00:00.000000000
2010-11-18T00:00:00.000000000
2010-11-19T00:00:00.000000000
2010-11-20T00:00:00.000000000
2010-11-21T00:00:00.000000000
2010-11-22T00:00:00.000000000
2010-11-23T00:00:00.000000000
2010-11-24T00:00:00.000000000
2010-11-25T00:00:00.000000000
2010-11-26T00:00:00.000000000
2010-11-27T00:00:00.000000000
2010-11-28T00:00:00.000000000
2010-11-29T00:00:00.000000000
2010-11-30T00:00:00.000000000
2010-12-01T00:00:00.000000000
2010-12-02T00:00:00.000000000
2010-12-03T00:00:00.000000000
2010-12-04T00:00:00.000000000
2010-12-05T00:00:00.000000000
2010-12-06T00:00:00.000000000
2010-12-07T00:00:00.000000000
2010-12-08T00:00:00.000000000
2010-12-09T00:00:00.000000000
2010-12-10T00:00:00.000000000
2010-12-11T00:00:00.000000000
2010-12-12T00:00:00.000000000
2010-12-13T00:00:00.000000000
2010-12-14T00:00:00.000000000
2010-12-15T00:00:00.000000000
2010-12-16T00:00:00.000000000
2010-12-17T00:00:00.000000000
2010-12-18T00:00:00.000000000
2010-12-19T00:00:00.000000000
2010-12-20T00:00:00.000000000
2010-12-21T00:00:00.000000000
2010-12-22T00:00:00.000000000
2010-12-23T00:00:00.000000000
2010-12-24T00:00:00.000000000
2010-12-25T00:00:00.000000000
2010-12-26T00:00:00.000000000
2010-12-27T00:00:00.000000000
2010-12-28T00:00:00.000000000
2010-12-29T00:00:00.000000000
2010-12-30T00:00:00.000000000
2010-12-31T00:00:00.000000000
2011-01-01T00:00:00.000000000
2011-01-02T00:00:00.000000000
2011-01-03T00:00:00.000000000
2011-01-04T00:00:00.000000000
2011-01-05T00:00:00.000000000
2011-01-06T00:00:00.000000000
2011-01-07T00:00:00.000000000
2011-01-08T00:00:00.000000000
2011-01-09T00:00:00.000000000
2011-01-10T00:00:00.000000000
2011-01-11T00:00:00.000000000
2011-01-12T00:00:00.000000000
2011-01-13T00:00:00.000000000
2011-01-14T00:00:00.000000000
2011-01-15T00:00:00.000000000
2011-01-16T00:00:00.000000000
2011-01-17T00:00:00.000000000
2011-01-18T00:00:00.000000000
2011-01-19T00:00:00.000000000
2011-01-20T00:00:00.000000000
2011-01-21T00:00:00.000000000
2011-01-22T00:00:00.000000000
2011-01-23T00:00:00.000000000
2011-01-24T00:00:00.000000000
2011-01-25T00:00:00.000000000
2011-01-26T00:00:00.000000000
2011-01-27T00:00:00.000000000
2011-01-28T00:00:00.000000000
2011-01-29T00:00:00.000000000
2011-01-30T00:00:00.000000000
2011-01-31T00:00:00.000000000
2011-02-01T00:00:00.000000000
2011-02-02T00:00:00.000000000
2011-02-03T00:00:00.000000000
2011-02-04T00:00:00.000000000
2011-02-05T00:00:00.000000000
2011-02-06T00:00:00.000000000
2011-02-07T00:00:00.000000000
2011-02-08T00:00:00.000000000
2011-02-09T00:00:00.000000000
2011-02-10T00:00:00.000000000
2011-02-11T00:00:00.000000000
2011-02-12T00:00:00.000000000
2011-02-13T00:00:00.000000000
2011-02-14T00:00:00.000000000
2011-02-15T00:00:00.000000000
2011-02-16T00:00:00.000000000
2011-02-17T00:00:00.000000000
2011-02-18T00:00:00.000000000
2011-02-19T00:00:00.000000000
2011-02-20T00:00:00.000000000
2011-02-21T00:00:00.000000000
2011-02-22T00:00:00.000000000
2011-02-23T00:00:00.000000000
2011-02-24T00:00:00.000000000
2011-02-25T00:00:00.000000000
2011-02-26T00:00:00.000000000
2011-02-27T00:00:00.000000000
2011-02-28T00:00:00.000000000
2011-03-01T00:00:00.000000000
2011-03-02T00:00:00.000000000
2011-03-03T00:00:00.000000000
2011-03-04T00:00:00.000000000
2011-03-05T00:00:00.000000000
2011-03-06T00:00:00.000000000
2011-03-07T00:00:00.000000000
2011-03-08T00:00:00.000000000
2011-03-09T00:00:00.000000000
2011-03-10T00:00:00.000000000
2011-03-11T00:00:00.000000000
2011-03-12T00:00:00.000000000
2011-03-13T00:00:00.000000000
2011-03-14T00:00:00.000000000
2011-03-15T00:00:00.000000000
2011-03-16T00:00:00.000000000
2011-03-17T00:00:00.000000000
2011-03-18T00:00:00.000000000
2011-03-19T00:00:00.000000000
2011-03-20T00:00:00.000000000
2011-03-21T00:00:00.000000000
2011-03-22T00:00:00.000000000
2011-03-23T00:00:00.000000000
2011-03-24T00:00:00.000000000
2011-03-25T00:00:00.000000000
2011-03-26T00:00:00.000000000
2011-03-27T00:00:00.000000000
2011-03-28T00:00:00.000000000
2011-03-29T00:00:00.000000000
2011-03-30T00:00:00.000000000
2011-03-31T00:00:00.000000000
2011-04-01T00:00:00.000000000
2011-04-02T00:00:00.000000000
2011-04-03T00:00:00.000000000
2011-04-04T00:00:00.000000000
2011-04-05T00:00:00.000000000
2011-04-06T00:00:00.000000000
2011-04-07T00:00:00.000000000
2011-04-08T00:00:00.000000000
2011-04-09T00:00:00.000000000
2011-04-10T00:00:00.000000000
2011-04-11T00:00:00.000000000
2011-04-12T00:00:00.000000000
2011-04-13T00:00:00.000000000
2011-04-14T00:00:00.000000000
2011-04-15T00:00:00.000000000
2011-04-16T00:00:00.000000000
2011-04-17T00:00:00.000000000
2011-04-18T00:00:00.000000000
2011-04-19T00:00:00.000000000
2011-04-20T00:00:00.000000000
2011-04-21T00:00:00.000000000
2011-04-22T00:00:00.000000000
2011-04-23T00:00:00.000000000
2011-04-24T00:00:00.000000000
2011-04-25T00:00:00.000000000
2011-04-26T00:00:00.000000000
2011-04-27T00:00:00.000000000
2011-04-28T00:00:00.000000000
2011-04-29T00:00:00.000000000
2011-04-30T00:00:00.000000000
2011-05-01T00:00:00.000000000
2011-05-02T00:00:00.000000000
2011-05-03T00:00:00.000000000
2011-05-04T00:00:00.000000000
2011-05-05T00:00:00.000000000
2011-05-06T00:00:00.000000000
2011-05-07T00:00:00.000000000
2011-05-08T00:00:00.000000000
2011-05-09T00:00:00.000000000
2011-05-10T00:00:00.000000000
2011-05-11T00:00:00.000000000
2011-05-12T00:00:00.000000000
2011-05-13T00:00:00.000000000
2011-05-14T00:00:00.000000000
2011-05-15T00:00:00.000000000
2011-05-16T00:00:00.000000000
2011-05-17T00:00:00.000000000
2011-05-18T00:00:00.000000000
2011-05-19T00:00:00.000000000
2011-05-20T00:00:00.000000000
2011-05-21T00:00:00.000000000
2011-05-22T00:00:00.000000000
2011-05-23T00:00:00.000000000
2011-05-24T00:00:00.000000000
2011-05-25T00:00:00.000000000
2011-05-26T00:00:00.000000000
2011-05-27T00:00:00.000000000
2011-05-28T00:00:00.000000000
2011-05-29T00:00:00.000000000
2011-05-30T00:00:00.000000000
2011-05-31T00:00:00.000000000
2011-06-01T00:00:00.000000000
2011-06-02T00:00:00.000000000
2011-06-03T00:00:00.000000000
2011-06-04T00:00:00.000000000

2011-06-05T00:00:00.000000000
2011-06-06T00:00:00.000000000
2011-06-07T00:00:00.000000000
2011-06-08T00:00:00.000000000
2011-06-09T00:00:00.000000000
2011-06-10T00:00:00.000000000
2011-06-11T00:00:00.000000000
2011-06-12T00:00:00.000000000
2011-06-13T00:00:00.000000000
2011-06-14T00:00:00.000000000
2011-06-15T00:00:00.000000000
2011-06-16T00:00:00.000000000
2011-06-17T00:00:00.000000000
2011-06-18T00:00:00.000000000
2011-06-19T00:00:00.000000000
2011-06-20T00:00:00.000000000
2011-06-21T00:00:00.000000000
2011-06-22T00:00:00.000000000
2011-06-23T00:00:00.000000000
2011-06-24T00:00:00.000000000
2011-06-25T00:00:00.000000000
2011-06-26T00:00:00.000000000
2011-06-27T00:00:00.000000000
2011-06-28T00:00:00.000000000
2011-06-29T00:00:00.000000000
2011-06-30T00:00:00.000000000
2011-07-01T00:00:00.000000000
2011-07-02T00:00:00.000000000
2011-07-03T00:00:00.000000000
2011-07-04T00:00:00.000000000
2011-07-05T00:00:00.000000000
2011-07-06T00:00:00.000000000
2011-07-07T00:00:00.000000000
2011-07-08T00:00:00.000000000
2011-07-09T00:00:00.000000000
2011-07-10T00:00:00.000000000
2011-07-11T00:00:00.000000000
2011-07-12T00:00:00.000000000
2011-07-13T00:00:00.000000000
2011-07-14T00:00:00.000000000
2011-07-15T00:00:00.000000000
2011-07-16T00:00:00.000000000
2011-07-17T00:00:00.000000000
2011-07-18T00:00:00.000000000
2011-07-19T00:00:00.000000000
2011-07-20T00:00:00.000000000
2011-07-21T00:00:00.000000000
2011-07-22T00:00:00.000000000
2011-07-23T00:00:00.000000000
2011-07-24T00:00:00.000000000
2011-07-25T00:00:00.000000000
2011-07-26T00:00:00.000000000
2011-07-27T00:00:00.000000000
2011-07-28T00:00:00.000000000
2011-07-29T00:00:00.000000000
2011-07-30T00:00:00.000000000
2011-07-31T00:00:00.000000000
2011-08-01T00:00:00.000000000
2011-08-02T00:00:00.000000000
2011-08-03T00:00:00.000000000
2011-08-04T00:00:00.000000000
2011-08-05T00:00:00.000000000
2011-08-06T00:00:00.000000000
2011-08-07T00:00:00.000000000
2011-08-08T00:00:00.000000000
2011-08-09T00:00:00.000000000
2011-08-10T00:00:00.000000000
2011-08-11T00:00:00.000000000
2011-08-12T00:00:00.000000000
2011-08-13T00:00:00.000000000
2011-08-14T00:00:00.000000000
2011-08-15T00:00:00.000000000
2011-08-16T00:00:00.000000000
2011-08-17T00:00:00.000000000
2011-08-18T00:00:00.000000000
2011-08-19T00:00:00.000000000
2011-08-20T00:00:00.000000000
2011-08-21T00:00:00.000000000
2011-08-22T00:00:00.000000000
2011-08-23T00:00:00.000000000
2011-08-24T00:00:00.000000000
2011-08-25T00:00:00.000000000
2011-08-26T00:00:00.000000000
2011-08-27T00:00:00.000000000
2011-08-28T00:00:00.000000000
2011-08-29T00:00:00.000000000
2011-08-30T00:00:00.000000000
2011-08-31T00:00:00.000000000
2011-09-01T00:00:00.000000000
2011-09-02T00:00:00.000000000
2011-09-03T00:00:00.000000000
2011-09-04T00:00:00.000000000
2011-09-05T00:00:00.000000000
2011-09-06T00:00:00.000000000
2011-09-07T00:00:00.000000000
2011-09-08T00:00:00.000000000
2011-09-09T00:00:00.000000000
2011-09-10T00:00:00.000000000
2011-09-11T00:00:00.000000000
2011-09-12T00:00:00.000000000
2011-09-13T00:00:00.000000000
2011-09-14T00:00:00.000000000
2011-09-15T00:00:00.000000000
2011-09-16T00:00:00.000000000
2011-09-17T00:00:00.000000000
2011-09-18T00:00:00.000000000
2011-09-19T00:00:00.000000000
2011-09-20T00:00:00.000000000
2011-09-21T00:00:00.000000000
2011-09-22T00:00:00.000000000
2011-09-23T00:00:00.000000000
2011-09-24T00:00:00.000000000
2011-09-25T00:00:00.000000000
2011-09-26T00:00:00.000000000
2011-09-27T00:00:00.000000000
2011-09-28T00:00:00.000000000
2011-09-29T00:00:00.000000000
2011-09-30T00:00:00.000000000
2011-10-01T00:00:00.000000000
2011-10-02T00:00:00.000000000
2011-10-03T00:00:00.000000000
2011-10-04T00:00:00.000000000
2011-10-05T00:00:00.000000000
2011-10-06T00:00:00.000000000
2011-10-07T00:00:00.000000000
2011-10-08T00:00:00.000000000
2011-10-09T00:00:00.000000000
2011-10-10T00:00:00.000000000
2011-10-11T00:00:00.000000000
2011-10-12T00:00:00.000000000
2011-10-13T00:00:00.000000000
2011-10-14T00:00:00.000000000
2011-10-15T00:00:00.000000000
2011-10-16T00:00:00.000000000
2011-10-17T00:00:00.000000000
2011-10-18T00:00:00.000000000
2011-10-19T00:00:00.000000000
2011-10-20T00:00:00.000000000
2011-10-21T00:00:00.000000000
2011-10-22T00:00:00.000000000
2011-10-23T00:00:00.000000000
2011-10-24T00:00:00.000000000
2011-10-25T00:00:00.000000000
2011-10-26T00:00:00.000000000
2011-10-27T00:00:00.000000000
2011-10-28T00:00:00.000000000
2011-10-29T00:00:00.000000000
2011-10-30T00:00:00.000000000
2011-10-31T00:00:00.000000000
2011-11-01T00:00:00.000000000
2011-11-02T00:00:00.000000000
2011-11-03T00:00:00.000000000
2011-11-04T00:00:00.000000000
2011-11-05T00:00:00.000000000
2011-11-06T00:00:00.000000000
2011-11-07T00:00:00.000000000
2011-11-08T00:00:00.000000000
2011-11-09T00:00:00.000000000
2011-11-10T00:00:00.000000000
2011-11-11T00:00:00.000000000
2011-11-12T00:00:00.000000000
2011-11-13T00:00:00.000000000
2011-11-14T00:00:00.000000000
2011-11-15T00:00:00.000000000
2011-11-16T00:00:00.000000000
2011-11-17T00:00:00.000000000
2011-11-18T00:00:00.000000000
2011-11-19T00:00:00.000000000
2011-11-20T00:00:00.000000000
2011-11-21T00:00:00.000000000
2011-11-22T00:00:00.000000000
2011-11-23T00:00:00.000000000
2011-11-24T00:00:00.000000000
2011-11-25T00:00:00.000000000
2011-11-26T00:00:00.000000000
2011-11-27T00:00:00.000000000
2011-11-28T00:00:00.000000000
2011-11-29T00:00:00.000000000
2011-11-30T00:00:00.000000000
2011-12-01T00:00:00.000000000
2011-12-02T00:00:00.000000000
2011-12-03T00:00:00.000000000
2011-12-04T00:00:00.000000000
2011-12-05T00:00:00.000000000
2011-12-06T00:00:00.000000000
2011-12-07T00:00:00.000000000
2011-12-08T00:00:00.000000000
2011-12-09T00:00:00.000000000
2011-12-10T00:00:00.000000000
2011-12-11T00:00:00.000000000
2011-12-12T00:00:00.000000000
2011-12-13T00:00:00.000000000
2011-12-14T00:00:00.000000000
2011-12-15T00:00:00.000000000
2011-12-16T00:00:00.000000000
2011-12-17T00:00:00.000000000
2011-12-18T00:00:00.000000000
2011-12-19T00:00:00.000000000
2011-12-20T00:00:00.000000000
2011-12-21T00:00:00.000000000
2011-12-22T00:00:00.000000000
2011-12-23T00:00:00.000000000
2011-12-24T00:00:00.000000000
2011-12-25T00:00:00.000000000
2011-12-26T00:00:00.000000000
2011-12-27T00:00:00.000000000
2011-12-28T00:00:00.000000000
2011-12-29T00:00:00.000000000
2011-12-30T00:00:00.000000000
2011-12-31T00:00:00.000000000
2012-01-01T00:00:00.000000000
2012-01-02T00:00:00.000000000
2012-01-03T00:00:00.000000000
2012-01-04T00:00:00.000000000
2012-01-05T00:00:00.000000000
2012-01-06T00:00:00.000000000
2012-01-07T00:00:00.000000000
2012-01-08T00:00:00.000000000
2012-01-09T00:00:00.000000000
2012-01-10T00:00:00.000000000
2012-01-11T00:00:00.000000000
2012-01-12T00:00:00.000000000
2012-01-13T00:00:00.000000000
2012-01-14T00:00:00.000000000
2012-01-15T00:00:00.000000000
2012-01-16T00:00:00.000000000
2012-01-17T00:00:00.000000000
2012-01-18T00:00:00.000000000
2012-01-19T00:00:00.000000000
2012-01-20T00:00:00.000000000
2012-01-21T00:00:00.000000000
2012-01-22T00:00:00.000000000
2012-01-23T00:00:00.000000000
2012-01-24T00:00:00.000000000
2012-01-25T00:00:00.000000000
2012-01-26T00:00:00.000000000
2012-01-27T00:00:00.000000000
2012-01-28T00:00:00.000000000
2012-01-29T00:00:00.000000000
2012-01-30T00:00:00.000000000
2012-01-31T00:00:00.000000000
2012-02-01T00:00:00.000000000
2012-02-02T00:00:00.000000000
2012-02-03T00:00:00.000000000
2012-02-04T00:00:00.000000000
2012-02-05T00:00:00.000000000
2012-02-06T00:00:00.000000000
2012-02-07T00:00:00.000000000
2012-02-08T00:00:00.000000000
2012-02-09T00:00:00.000000000
2012-02-10T00:00:00.000000000
2012-02-11T00:00:00.000000000
2012-02-12T00:00:00.000000000
2012-02-13T00:00:00.000000000
2012-02-14T00:00:00.000000000
2012-02-15T00:00:00.000000000
2012-02-16T00:00:00.000000000
2012-02-17T00:00:00.000000000
2012-02-18T00:00:00.000000000
2012-02-19T00:00:00.000000000
2012-02-20T00:00:00.000000000
2012-02-21T00:00:00.000000000
2012-02-22T00:00:00.000000000
2012-02-23T00:00:00.000000000
2012-02-24T00:00:00.000000000
2012-02-25T00:00:00.000000000
2012-02-26T00:00:00.000000000
2012-02-27T00:00:00.000000000
2012-02-28T00:00:00.000000000
2012-02-29T00:00:00.000000000
2012-03-01T00:00:00.000000000
2012-03-02T00:00:00.000000000
2012-03-03T00:00:00.000000000
2012-03-04T00:00:00.000000000
2012-03-05T00:00:00.000000000

2012-03-06T00:00:00.000000000
2012-03-07T00:00:00.000000000
2012-03-08T00:00:00.000000000
2012-03-09T00:00:00.000000000
2012-03-10T00:00:00.000000000
2012-03-11T00:00:00.000000000
2012-03-12T00:00:00.000000000
2012-03-13T00:00:00.000000000
2012-03-14T00:00:00.000000000
2012-03-15T00:00:00.000000000
2012-03-16T00:00:00.000000000
2012-03-17T00:00:00.000000000
2012-03-18T00:00:00.000000000
2012-03-19T00:00:00.000000000
2012-03-20T00:00:00.000000000
2012-03-21T00:00:00.000000000
2012-03-22T00:00:00.000000000
2012-03-23T00:00:00.000000000
2012-03-24T00:00:00.000000000
2012-03-25T00:00:00.000000000
2012-03-26T00:00:00.000000000
2012-03-27T00:00:00.000000000
2012-03-28T00:00:00.000000000
2012-03-29T00:00:00.000000000
2012-03-30T00:00:00.000000000
2012-03-31T00:00:00.000000000
2012-04-01T00:00:00.000000000
2012-04-02T00:00:00.000000000
2012-04-03T00:00:00.000000000
2012-04-04T00:00:00.000000000
2012-04-05T00:00:00.000000000
2012-04-06T00:00:00.000000000
2012-04-07T00:00:00.000000000
2012-04-08T00:00:00.000000000
2012-04-09T00:00:00.000000000
2012-04-10T00:00:00.000000000
2012-04-11T00:00:00.000000000
2012-04-12T00:00:00.000000000
2012-04-13T00:00:00.000000000
2012-04-14T00:00:00.000000000
2012-04-15T00:00:00.000000000
2012-04-16T00:00:00.000000000
2012-04-17T00:00:00.000000000
2012-04-18T00:00:00.000000000
2012-04-19T00:00:00.000000000
2012-04-20T00:00:00.000000000
2012-04-21T00:00:00.000000000
2012-04-22T00:00:00.000000000
2012-04-23T00:00:00.000000000
2012-04-24T00:00:00.000000000
2012-04-25T00:00:00.000000000
2012-04-26T00:00:00.000000000
2012-04-27T00:00:00.000000000
2012-04-28T00:00:00.000000000
2012-04-29T00:00:00.000000000
2012-04-30T00:00:00.000000000
2012-05-01T00:00:00.000000000
2012-05-02T00:00:00.000000000
2012-05-03T00:00:00.000000000
2012-05-04T00:00:00.000000000
2012-05-05T00:00:00.000000000
2012-05-06T00:00:00.000000000
2012-05-07T00:00:00.000000000
2012-05-08T00:00:00.000000000
2012-05-09T00:00:00.000000000
2012-05-10T00:00:00.000000000
2012-05-11T00:00:00.000000000
2012-05-12T00:00:00.000000000
2012-05-13T00:00:00.000000000
2012-05-14T00:00:00.000000000
2012-05-15T00:00:00.000000000
2012-05-16T00:00:00.000000000
2012-05-17T00:00:00.000000000
2012-05-18T00:00:00.000000000
2012-05-19T00:00:00.000000000
2012-05-20T00:00:00.000000000
2012-05-21T00:00:00.000000000
2012-05-22T00:00:00.000000000
2012-05-23T00:00:00.000000000
2012-05-24T00:00:00.000000000
2012-05-25T00:00:00.000000000
2012-05-26T00:00:00.000000000
2012-05-27T00:00:00.000000000
2012-05-28T00:00:00.000000000
2012-05-29T00:00:00.000000000
2012-05-30T00:00:00.000000000
2012-05-31T00:00:00.000000000
2012-06-01T00:00:00.000000000
2012-06-02T00:00:00.000000000
2012-06-03T00:00:00.000000000
2012-06-04T00:00:00.000000000
2012-06-05T00:00:00.000000000
2012-06-06T00:00:00.000000000
2012-06-07T00:00:00.000000000
2012-06-08T00:00:00.000000000
2012-06-09T00:00:00.000000000
2012-06-10T00:00:00.000000000
2012-06-11T00:00:00.000000000
2012-06-12T00:00:00.000000000
2012-06-13T00:00:00.000000000
2012-06-14T00:00:00.000000000
2012-06-15T00:00:00.000000000
2012-06-16T00:00:00.000000000
2012-06-17T00:00:00.000000000
2012-06-18T00:00:00.000000000
2012-06-19T00:00:00.000000000
2012-06-20T00:00:00.000000000
2012-06-21T00:00:00.000000000
2012-06-22T00:00:00.000000000
2012-06-23T00:00:00.000000000
2012-06-24T00:00:00.000000000
2012-06-25T00:00:00.000000000
2012-06-26T00:00:00.000000000
2012-06-27T00:00:00.000000000
2012-06-28T00:00:00.000000000
2012-06-29T00:00:00.000000000
2012-06-30T00:00:00.000000000
2012-07-01T00:00:00.000000000
2012-07-02T00:00:00.000000000
2012-07-03T00:00:00.000000000
2012-07-04T00:00:00.000000000
2012-07-05T00:00:00.000000000
2012-07-06T00:00:00.000000000
2012-07-07T00:00:00.000000000
2012-07-08T00:00:00.000000000
2012-07-09T00:00:00.000000000
2012-07-10T00:00:00.000000000
2012-07-11T00:00:00.000000000
2012-07-12T00:00:00.000000000
2012-07-13T00:00:00.000000000
2012-07-14T00:00:00.000000000
2012-07-15T00:00:00.000000000
2012-07-16T00:00:00.000000000
2012-07-17T00:00:00.000000000
2012-07-18T00:00:00.000000000
2012-07-19T00:00:00.000000000
2012-07-20T00:00:00.000000000
2012-07-21T00:00:00.000000000
2012-07-22T00:00:00.000000000
2012-07-23T00:00:00.000000000
2012-07-24T00:00:00.000000000
2012-07-25T00:00:00.000000000
2012-07-26T00:00:00.000000000
2012-07-27T00:00:00.000000000
2012-07-28T00:00:00.000000000
2012-07-29T00:00:00.000000000
2012-07-30T00:00:00.000000000
2012-07-31T00:00:00.000000000
2012-08-01T00:00:00.000000000
2012-08-02T00:00:00.000000000
2012-08-03T00:00:00.000000000
2012-08-04T00:00:00.000000000
2012-08-05T00:00:00.000000000
2012-08-06T00:00:00.000000000
2012-08-07T00:00:00.000000000
2012-08-08T00:00:00.000000000
2012-08-09T00:00:00.000000000
2012-08-10T00:00:00.000000000
2012-08-11T00:00:00.000000000
2012-08-12T00:00:00.000000000
2012-08-13T00:00:00.000000000
2012-08-14T00:00:00.000000000
2012-08-15T00:00:00.000000000
2012-08-16T00:00:00.000000000
2012-08-17T00:00:00.000000000
2012-08-18T00:00:00.000000000
2012-08-19T00:00:00.000000000
2012-08-20T00:00:00.000000000
2012-08-21T00:00:00.000000000
2012-08-22T00:00:00.000000000
2012-08-23T00:00:00.000000000
2012-08-24T00:00:00.000000000
2012-08-25T00:00:00.000000000
2012-08-26T00:00:00.000000000
2012-08-27T00:00:00.000000000
2012-08-28T00:00:00.000000000
2012-08-29T00:00:00.000000000
2012-08-30T00:00:00.000000000
2012-08-31T00:00:00.000000000
2012-09-01T00:00:00.000000000
2012-09-02T00:00:00.000000000
2012-09-03T00:00:00.000000000
2012-09-04T00:00:00.000000000
2012-09-05T00:00:00.000000000
2012-09-06T00:00:00.000000000
2012-09-07T00:00:00.000000000
2012-09-08T00:00:00.000000000
2012-09-09T00:00:00.000000000
2012-09-10T00:00:00.000000000
2012-09-11T00:00:00.000000000
2012-09-12T00:00:00.000000000
2012-09-13T00:00:00.000000000
2012-09-14T00:00:00.000000000
2012-09-15T00:00:00.000000000
2012-09-16T00:00:00.000000000
2012-09-17T00:00:00.000000000
2012-09-18T00:00:00.000000000
2012-09-19T00:00:00.000000000
2012-09-20T00:00:00.000000000
2012-09-21T00:00:00.000000000
2012-09-22T00:00:00.000000000
2012-09-23T00:00:00.000000000
2012-09-24T00:00:00.000000000
2012-09-25T00:00:00.000000000
2012-09-26T00:00:00.000000000
2012-09-27T00:00:00.000000000
2012-09-28T00:00:00.000000000
2012-09-29T00:00:00.000000000
2012-10-03T00:00:00.000000000
2012-10-04T00:00:00.000000000
2012-10-05T00:00:00.000000000
2012-10-06T00:00:00.000000000
2012-10-07T00:00:00.000000000
2012-10-08T00:00:00.000000000
2012-10-09T00:00:00.000000000
2012-10-10T00:00:00.000000000
2012-10-11T00:00:00.000000000
2012-10-12T00:00:00.000000000
2012-10-13T00:00:00.000000000
2012-10-14T00:00:00.000000000
2012-10-15T00:00:00.000000000
2012-10-16T00:00:00.000000000
2012-10-17T00:00:00.000000000
2012-10-18T00:00:00.000000000
2012-10-19T00:00:00.000000000
2012-10-20T00:00:00.000000000
2012-10-21T00:00:00.000000000
2012-10-22T00:00:00.000000000
2012-10-23T00:00:00.000000000
2012-10-24T00:00:00.000000000
2012-10-25T00:00:00.000000000
2012-10-26T00:00:00.000000000
2012-10-27T00:00:00.000000000
2012-10-28T00:00:00.000000000
2012-10-29T00:00:00.000000000
2012-10-30T00:00:00.000000000
2012-10-31T00:00:00.000000000
2012-11-01T00:00:00.000000000
2012-11-02T00:00:00.000000000
2012-11-03T00:00:00.000000000
2012-11-04T00:00:00.000000000
2012-11-05T00:00:00.000000000
2012-11-06T00:00:00.000000000
2012-11-07T00:00:00.000000000
2012-11-08T00:00:00.000000000
2012-11-09T00:00:00.000000000
2012-11-10T00:00:00.000000000
2012-11-11T00:00:00.000000000
2012-11-12T00:00:00.000000000
2012-11-13T00:00:00.000000000
2012-11-14T00:00:00.000000000
2012-11-15T00:00:00.000000000
2012-11-16T00:00:00.000000000
2012-11-17T00:00:00.000000000
2012-11-18T00:00:00.000000000
2012-11-19T00:00:00.000000000
2012-11-20T00:00:00.000000000
2012-11-21T00:00:00.000000000
2012-11-22T00:00:00.000000000
2012-11-23T00:00:00.000000000
2012-11-24T00:00:00.000000000
2012-11-25T00:00:00.000000000
2012-11-26T00:00:00.000000000
2012-11-27T00:00:00.000000000
2012-11-28T00:00:00.000000000
2012-11-29T00:00:00.000000000
2012-11-30T00:00:00.000000000
2012-12-01T00:00:00.000000000
2012-12-02T00:00:00.000000000
2012-12-03T00:00:00.000000000
2012-12-04T00:00:00.000000000
2012-12-05T00:00:00.000000000
2012-12-06T00:00:00.000000000
2012-12-07T00:00:00.000000000
2012-12-08T00:00:00.000000000

2012-12-09T00:00:00.000000000
2012-12-10T00:00:00.000000000
2012-12-11T00:00:00.000000000
2012-12-12T00:00:00.000000000
2012-12-13T00:00:00.000000000
2012-12-14T00:00:00.000000000
2012-12-15T00:00:00.000000000
2012-12-16T00:00:00.000000000
2012-12-17T00:00:00.000000000
2012-12-18T00:00:00.000000000
2012-12-19T00:00:00.000000000
2012-12-20T00:00:00.000000000
2012-12-21T00:00:00.000000000
2012-12-22T00:00:00.000000000
2012-12-23T00:00:00.000000000
2012-12-24T00:00:00.000000000
2012-12-25T00:00:00.000000000
2012-12-26T00:00:00.000000000
2012-12-27T00:00:00.000000000
2012-12-28T00:00:00.000000000
2012-12-29T00:00:00.000000000
2012-12-30T00:00:00.000000000
2012-12-31T00:00:00.000000000
2013-01-01T00:00:00.000000000
2013-01-02T00:00:00.000000000
2013-01-03T00:00:00.000000000
2013-01-04T00:00:00.000000000
2013-01-05T00:00:00.000000000
2013-01-06T00:00:00.000000000
2013-01-07T00:00:00.000000000
2013-01-08T00:00:00.000000000
2013-01-09T00:00:00.000000000
2013-01-10T00:00:00.000000000
2013-01-11T00:00:00.000000000
2013-01-12T00:00:00.000000000
2013-01-13T00:00:00.000000000
2013-01-14T00:00:00.000000000
2013-01-15T00:00:00.000000000
2013-01-16T00:00:00.000000000
2013-01-17T00:00:00.000000000
2013-01-18T00:00:00.000000000
2013-01-19T00:00:00.000000000
2013-01-20T00:00:00.000000000
2013-01-21T00:00:00.000000000
2013-01-22T00:00:00.000000000
2013-01-23T00:00:00.000000000
2013-01-24T00:00:00.000000000
2013-01-25T00:00:00.000000000
2013-01-26T00:00:00.000000000
2013-01-27T00:00:00.000000000
2013-01-28T00:00:00.000000000
2013-01-29T00:00:00.000000000
2013-01-30T00:00:00.000000000
2013-01-31T00:00:00.000000000
2013-02-01T00:00:00.000000000
2013-02-02T00:00:00.000000000
2013-02-03T00:00:00.000000000
2013-02-04T00:00:00.000000000
2013-02-05T00:00:00.000000000
2013-02-06T00:00:00.000000000
2013-02-07T00:00:00.000000000
2013-02-08T00:00:00.000000000
2013-02-09T00:00:00.000000000
2013-02-10T00:00:00.000000000
2013-02-11T00:00:00.000000000
2013-02-12T00:00:00.000000000
2013-02-13T00:00:00.000000000
2013-02-14T00:00:00.000000000
2013-02-15T00:00:00.000000000
2013-02-16T00:00:00.000000000
2013-02-17T00:00:00.000000000
2013-02-18T00:00:00.000000000
2013-02-19T00:00:00.000000000
2013-02-20T00:00:00.000000000
2013-02-21T00:00:00.000000000
2013-02-22T00:00:00.000000000
2013-02-23T00:00:00.000000000
2013-02-24T00:00:00.000000000
2013-02-25T00:00:00.000000000
2013-02-26T00:00:00.000000000
2013-02-27T00:00:00.000000000
2013-02-28T00:00:00.000000000
2013-03-01T00:00:00.000000000
2013-03-02T00:00:00.000000000
2013-03-03T00:00:00.000000000
2013-03-04T00:00:00.000000000
2013-03-05T00:00:00.000000000
2013-03-06T00:00:00.000000000
2013-03-07T00:00:00.000000000
2013-03-08T00:00:00.000000000
2013-03-09T00:00:00.000000000
2013-03-10T00:00:00.000000000
2013-03-11T00:00:00.000000000
2013-03-12T00:00:00.000000000
2013-03-13T00:00:00.000000000
2013-03-14T00:00:00.000000000
2013-03-15T00:00:00.000000000
2013-03-16T00:00:00.000000000
2013-03-17T00:00:00.000000000
2013-03-18T00:00:00.000000000
2013-03-19T00:00:00.000000000
2013-03-20T00:00:00.000000000
2013-03-21T00:00:00.000000000
2013-03-22T00:00:00.000000000
2013-03-23T00:00:00.000000000
2013-03-24T00:00:00.000000000
2013-03-25T00:00:00.000000000
2013-03-26T00:00:00.000000000
2013-03-27T00:00:00.000000000
2013-03-28T00:00:00.000000000
2013-03-29T00:00:00.000000000
2013-03-30T00:00:00.000000000
2013-03-31T00:00:00.000000000
2013-04-01T00:00:00.000000000
2013-04-02T00:00:00.000000000
2013-04-03T00:00:00.000000000
2013-04-04T00:00:00.000000000
2013-04-05T00:00:00.000000000
2013-04-06T00:00:00.000000000
2013-04-07T00:00:00.000000000
2013-04-08T00:00:00.000000000
2013-04-09T00:00:00.000000000
2013-04-10T00:00:00.000000000
2013-04-11T00:00:00.000000000
2013-04-12T00:00:00.000000000
2013-04-13T00:00:00.000000000
2013-04-14T00:00:00.000000000
2013-04-15T00:00:00.000000000
2013-04-16T00:00:00.000000000
2013-04-17T00:00:00.000000000
2013-04-18T00:00:00.000000000
2013-04-19T00:00:00.000000000
2013-04-20T00:00:00.000000000
2013-04-21T00:00:00.000000000
2013-04-22T00:00:00.000000000
2013-04-23T00:00:00.000000000
2013-04-24T00:00:00.000000000
2013-04-25T00:00:00.000000000
2013-04-26T00:00:00.000000000
2013-04-27T00:00:00.000000000
2013-04-28T00:00:00.000000000
2013-04-29T00:00:00.000000000
2013-04-30T00:00:00.000000000
2013-05-01T00:00:00.000000000
2013-05-02T00:00:00.000000000
2013-05-03T00:00:00.000000000
2013-05-04T00:00:00.000000000
2013-05-05T00:00:00.000000000
2013-05-06T00:00:00.000000000
2013-05-07T00:00:00.000000000
2013-05-08T00:00:00.000000000
2013-05-09T00:00:00.000000000
2013-05-10T00:00:00.000000000
2013-05-11T00:00:00.000000000
2013-05-12T00:00:00.000000000
2013-05-13T00:00:00.000000000
2013-05-14T00:00:00.000000000
2013-05-15T00:00:00.000000000
2013-05-16T00:00:00.000000000
2013-05-17T00:00:00.000000000
2013-05-18T00:00:00.000000000
2013-05-19T00:00:00.000000000
2013-05-20T00:00:00.000000000
2013-05-21T00:00:00.000000000
2013-05-22T00:00:00.000000000
2013-05-23T00:00:00.000000000
2013-05-24T00:00:00.000000000
2013-05-25T00:00:00.000000000
2013-05-26T00:00:00.000000000
2013-05-27T00:00:00.000000000
2013-05-28T00:00:00.000000000
2013-05-29T00:00:00.000000000
2013-05-30T00:00:00.000000000
2013-05-31T00:00:00.000000000
2013-06-01T00:00:00.000000000
2013-06-02T00:00:00.000000000
2013-06-03T00:00:00.000000000
2013-06-04T00:00:00.000000000
2013-06-05T00:00:00.000000000
2013-06-06T00:00:00.000000000
2013-06-07T00:00:00.000000000
2013-06-08T00:00:00.000000000
2013-06-09T00:00:00.000000000
2013-06-10T00:00:00.000000000
2013-06-11T00:00:00.000000000
2013-06-12T00:00:00.000000000
2013-06-13T00:00:00.000000000
2013-06-14T00:00:00.000000000
2013-06-15T00:00:00.000000000
2013-06-16T00:00:00.000000000
2013-06-17T00:00:00.000000000
2013-06-18T00:00:00.000000000
2013-06-19T00:00:00.000000000
2013-06-20T00:00:00.000000000
2013-06-21T00:00:00.000000000
2013-06-22T00:00:00.000000000
2013-06-23T00:00:00.000000000
2013-06-24T00:00:00.000000000
2013-06-25T00:00:00.000000000
2013-06-26T00:00:00.000000000
2013-06-27T00:00:00.000000000
2013-06-28T00:00:00.000000000
2013-06-29T00:00:00.000000000
2013-06-30T00:00:00.000000000
2013-07-01T00:00:00.000000000
2013-07-02T00:00:00.000000000
2013-07-03T00:00:00.000000000
2013-07-04T00:00:00.000000000
2013-07-05T00:00:00.000000000
2013-07-06T00:00:00.000000000
2013-07-07T00:00:00.000000000
2013-07-08T00:00:00.000000000
2013-07-09T00:00:00.000000000
2013-07-10T00:00:00.000000000
2013-07-11T00:00:00.000000000
2013-07-12T00:00:00.000000000
2013-07-13T00:00:00.000000000
2013-07-14T00:00:00.000000000
2013-07-15T00:00:00.000000000
2013-07-16T00:00:00.000000000
2013-07-17T00:00:00.000000000
2013-07-18T00:00:00.000000000
2013-07-19T00:00:00.000000000
2013-07-20T00:00:00.000000000
2013-07-21T00:00:00.000000000
2013-07-22T00:00:00.000000000
2013-07-23T00:00:00.000000000
2013-07-24T00:00:00.000000000
2013-07-25T00:00:00.000000000
2013-07-26T00:00:00.000000000
2013-07-27T00:00:00.000000000
2013-07-28T00:00:00.000000000
2013-07-29T00:00:00.000000000
2013-07-30T00:00:00.000000000
2013-07-31T00:00:00.000000000
2013-08-01T00:00:00.000000000
2013-08-02T00:00:00.000000000
2013-08-03T00:00:00.000000000
2013-08-04T00:00:00.000000000
2013-08-05T00:00:00.000000000
2013-08-06T00:00:00.000000000
2013-08-07T00:00:00.000000000
2013-08-08T00:00:00.000000000
2013-08-09T00:00:00.000000000
2013-08-10T00:00:00.000000000
2013-08-11T00:00:00.000000000
2013-08-12T00:00:00.000000000
2013-08-13T00:00:00.000000000
2013-08-14T00:00:00.000000000
2013-08-15T00:00:00.000000000
2013-08-16T00:00:00.000000000
2013-08-17T00:00:00.000000000
2013-08-18T00:00:00.000000000
2013-08-19T00:00:00.000000000
2013-08-20T00:00:00.000000000
2013-08-21T00:00:00.000000000
2013-08-22T00:00:00.000000000
2013-08-23T00:00:00.000000000
2013-08-24T00:00:00.000000000
2013-08-25T00:00:00.000000000
2013-08-26T00:00:00.000000000
2013-08-27T00:00:00.000000000
2013-08-28T00:00:00.000000000
2013-08-29T00:00:00.000000000
2013-08-30T00:00:00.000000000
2013-08-31T00:00:00.000000000
2013-09-01T00:00:00.000000000
2013-09-02T00:00:00.000000000
2013-09-03T00:00:00.000000000
2013-09-04T00:00:00.000000000
2013-09-05T00:00:00.000000000
2013-09-06T00:00:00.000000000
2013-09-07T00:00:00.000000000
2013-09-08T00:00:00.000000000

2013-09-09T00:00:00.000000000
2013-09-10T00:00:00.000000000
2013-09-11T00:00:00.000000000
2013-09-12T00:00:00.000000000
2013-09-13T00:00:00.000000000
2013-09-14T00:00:00.000000000
2013-09-15T00:00:00.000000000
2013-09-16T00:00:00.000000000
2013-09-17T00:00:00.000000000
2013-09-18T00:00:00.000000000
2013-09-19T00:00:00.000000000
2013-09-20T00:00:00.000000000
2013-09-21T00:00:00.000000000
2013-09-22T00:00:00.000000000
2013-09-23T00:00:00.000000000
2013-09-24T00:00:00.000000000
2013-09-25T00:00:00.000000000
2013-09-26T00:00:00.000000000
2014-01-07T00:00:00.000000000
2014-01-08T00:00:00.000000000
2014-01-09T00:00:00.000000000
2014-01-10T00:00:00.000000000
2014-01-11T00:00:00.000000000
2014-01-12T00:00:00.000000000
2014-01-13T00:00:00.000000000
2014-01-14T00:00:00.000000000
2014-01-15T00:00:00.000000000
2014-01-16T00:00:00.000000000
2014-01-17T00:00:00.000000000
2014-01-18T00:00:00.000000000
2014-01-19T00:00:00.000000000
2014-01-20T00:00:00.000000000
2014-01-21T00:00:00.000000000
2014-01-22T00:00:00.000000000
2014-01-23T00:00:00.000000000
2014-01-24T00:00:00.000000000
2014-01-25T00:00:00.000000000
2014-01-26T00:00:00.000000000
2014-01-27T00:00:00.000000000
2014-01-28T00:00:00.000000000
2014-01-29T00:00:00.000000000
2014-01-30T00:00:00.000000000
2014-01-31T00:00:00.000000000
2014-02-01T00:00:00.000000000
2014-02-02T00:00:00.000000000
2014-02-03T00:00:00.000000000
2014-02-04T00:00:00.000000000
2014-02-05T00:00:00.000000000
2014-02-06T00:00:00.000000000
2014-02-07T00:00:00.000000000
2014-02-08T00:00:00.000000000
2014-02-09T00:00:00.000000000
2014-02-10T00:00:00.000000000
2014-02-11T00:00:00.000000000
2014-02-12T00:00:00.000000000
2014-02-13T00:00:00.000000000
2014-02-14T00:00:00.000000000
2014-02-15T00:00:00.000000000
2014-02-16T00:00:00.000000000
2014-02-17T00:00:00.000000000
2014-02-18T00:00:00.000000000
2014-02-19T00:00:00.000000000
2014-02-20T00:00:00.000000000
2014-02-21T00:00:00.000000000
2014-02-22T00:00:00.000000000
2014-02-23T00:00:00.000000000
2014-02-24T00:00:00.000000000
2014-02-25T00:00:00.000000000
2014-02-26T00:00:00.000000000
2014-02-27T00:00:00.000000000
2014-02-28T00:00:00.000000000
2014-03-01T00:00:00.000000000
2014-03-02T00:00:00.000000000
2014-03-03T00:00:00.000000000
2014-03-04T00:00:00.000000000
2014-03-05T00:00:00.000000000
2014-03-06T00:00:00.000000000
2014-03-09T00:00:00.000000000
2014-03-10T00:00:00.000000000
2014-03-11T00:00:00.000000000
2014-03-12T00:00:00.000000000
2014-03-13T00:00:00.000000000
2014-03-14T00:00:00.000000000
2014-03-15T00:00:00.000000000
2014-03-16T00:00:00.000000000
2014-03-17T00:00:00.000000000
2014-03-18T00:00:00.000000000
2014-03-19T00:00:00.000000000
2014-03-20T00:00:00.000000000
2014-03-21T00:00:00.000000000
2014-03-22T00:00:00.000000000
2014-03-23T00:00:00.000000000
2014-03-24T00:00:00.000000000
2014-03-25T00:00:00.000000000
2014-03-26T00:00:00.000000000
2014-03-27T00:00:00.000000000
2014-03-28T00:00:00.000000000
2014-03-29T00:00:00.000000000
2014-03-30T00:00:00.000000000
2014-03-31T00:00:00.000000000
2014-04-01T00:00:00.000000000
2014-04-02T00:00:00.000000000
2014-04-03T00:00:00.000000000
2014-04-04T00:00:00.000000000
2014-04-05T00:00:00.000000000
2014-04-06T00:00:00.000000000
2014-04-07T00:00:00.000000000
2014-04-08T00:00:00.000000000
2014-04-09T00:00:00.000000000
2014-04-10T00:00:00.000000000
2014-04-11T00:00:00.000000000
2014-04-12T00:00:00.000000000
2014-04-13T00:00:00.000000000
2014-04-14T00:00:00.000000000
2014-04-15T00:00:00.000000000
2014-04-16T00:00:00.000000000
2014-04-17T00:00:00.000000000
2014-04-18T00:00:00.000000000
2014-04-19T00:00:00.000000000
2014-04-20T00:00:00.000000000
2014-04-21T00:00:00.000000000
2014-04-22T00:00:00.000000000
2014-04-23T00:00:00.000000000
2014-04-24T00:00:00.000000000
2014-04-25T00:00:00.000000000
2014-04-26T00:00:00.000000000
2014-04-27T00:00:00.000000000
2014-04-28T00:00:00.000000000
2014-04-29T00:00:00.000000000
2014-04-30T00:00:00.000000000
2014-05-01T00:00:00.000000000
2014-05-02T00:00:00.000000000
2014-05-03T00:00:00.000000000
2014-05-04T00:00:00.000000000
2014-05-05T00:00:00.000000000
2014-05-06T00:00:00.000000000
2014-05-07T00:00:00.000000000
2014-05-08T00:00:00.000000000
2014-05-09T00:00:00.000000000
2014-05-10T00:00:00.000000000
2014-05-11T00:00:00.000000000
2014-05-12T00:00:00.000000000
2014-05-13T00:00:00.000000000

,city,state,price,amount,quality,date,ppg,state.name,lat,lon,dex
0,Annandale,VA,100,7.075,high,2010-09-02,14.13,Virginia,38.830345,-77.213870,0
1,Auburn,AL,60,28.300,high,2010-09-02,2.12,Alabama,32.578185,-85.472820,1
2,Austin,TX,60,28.300,medium,2010-09-02,2.12,Texas,30.326374,-97.771258,2
3,Belleville,IL,400,28.300,high,2010-09-02,14.13,Illinois,38.532311,-89.983521,3
4,Boone,NC,55,3.540,high,2010-09-02,15.54,North Carolina,36.217052,-81.687983,4